R'nvim.plugins.packer.install'

R'nvim.plugins.telescope'
R'nvim.plugins.nvim-tree'
R'nvim.plugins.vim-easymotion'
R'nvim.plugins.treesitter'
R'nvim.plugins.bufferline'
R'nvim.plugins.markdown-preview'
R'nvim.plugins.lualine'
R'nvim.plugins.colorscheme'
