require('nvim.plugins.packer.install')

require('nvim.plugins.comment-frame')
require('nvim.plugins.fugitive')
require('nvim.plugins.telescope')
require('nvim.plugins.nvim-tree')
require('nvim.plugins.vimspector')
require('nvim.plugins.nvim-terminal')
require('nvim.plugins.vim-easymotion')
require('nvim.plugins.treesitter')
require('nvim.plugins.bufferline')
require('nvim.plugins.markdown-preview')
require('nvim.plugins.lualine')
require('nvim.plugins.completion')
require('nvim.plugins.lsp')
require('nvim.plugins.lspinstall')
require('nvim.plugins.colorscheme')
