require('nvim.plugins.packer.install')

require('nvim.plugins.telescope')
require('nvim.plugins.nvim-tree')
require('nvim.plugins.vim-easymotion')
require('nvim.plugins.treesitter')
require('nvim.plugins.bufferline')
require('nvim.plugins.markdown-preview')
require('nvim.plugins.lualine')
require('nvim.plugins.colorscheme')
