Variable.g({
	coc_global_extensions = {
		'coc-actions',
		'coc-css',
		'coc-emmet',
		'coc-eslint',
		'coc-html',
		'coc-java',
		'coc-java-debug',
		'coc-json',
		'coc-markdownlint',
		'coc-snippets',
		'coc-spell-checker',
		'coc-tabnine',
		'coc-xml',
		'coc-yank',
		'coc-tsserver',
		'coc-prettier',
		'coc-psalm'
	}
})
